import React, { useState } from 'react';
import { Sparkles, Plus, Trash2, CheckCircle, Code } from 'lucide-react';
import { strategyApi } from '../../api/strategyApi';
import { useToast } from '../../context/ToastContext';

export const StrategyBuilderPage = ({ onNavigate }) => {
  const { addToast } = useToast();
  const [loading, setLoading] = useState(false);
  const [aiPrompt, setAiPrompt] = useState('');
  const [aiGenerating, setAiGenerating] = useState(false);

  // Form State
  const [name, setName] = useState('NIFTY 8/33 EMA Pullback Scalper');
  const [author, setAuthor] = useState('Admin Quant');
  const [description, setDescription] = useState('5m trend following option buying strategy using 8 EMA and 33 EMA crossover pullback');
  const [underlying, setUnderlying] = useState('NIFTY 50');
  const [timeframe, setTimeframe] = useState('5m');
  const [tradingHorizon, setTradingHorizon] = useState('Intraday');
  const [target, setTarget] = useState('2R');
  const [stopLoss, setStopLoss] = useState('Candle Low');
  const [maxLossPerTrade, setMaxLossPerTrade] = useState('2500');
  const [entryFrom, setEntryFrom] = useState('09:30');
  const [forcedExitTime, setForcedExitTime] = useState('15:15');

  const [legs, setLegs] = useState([
    { action: 'BUY', type: 'CE', strike: 'ATM', quantity: 1 },
  ]);

  const addLeg = () => {
    setLegs([...legs, { action: 'BUY', type: 'CE', strike: 'ATM', quantity: 1 }]);
  };

  const removeLeg = (index) => {
    setLegs(legs.filter((_, idx) => idx !== index));
  };

  const updateLeg = (index, field, value) => {
    const updated = [...legs];
    updated[index][field] = value;
    setLegs(updated);
  };

  const handleAiGenerate = async () => {
    if (!aiPrompt.trim()) {
      addToast('Please enter an AI prompt description', 'warning');
      return;
    }
    setAiGenerating(true);
    try {
      const res = await strategyApi.generateStrategyAI(aiPrompt);
      if (res.data) {
        const d = res.data;
        setName(d.name || name);
        setDescription(d.description || description);
        setUnderlying(d.underlying || underlying);
        setTimeframe(d.timeframe || timeframe);
        addToast('Strategy schema generated by AI successfully!', 'success');
      }
    } catch (err) {
      addToast(err.message || 'AI Generation fallback to smart defaults', 'info');
      // Smart populate
      setName('AI Generated Momentum Breakout');
      setDescription(aiPrompt);
    } finally {
      setAiGenerating(false);
    }
  };

  const handleSaveStrategy = async (e) => {
    e.preventDefault();
    setLoading(true);

    const payload = {
      name,
      author,
      description,
      tradingHorizon,
      timeframe,
      entryTimeframe: timeframe,
      instrumentType: 'Options',
      underlying,
      target,
      status: 'ACTIVE_LIVE',
      entryConditions: [
        '8 EMA is above 33 EMA for bullish setup',
        'Price pulls back toward 8 EMA',
      ],
      exitConditions: [
        `Target of ${target} is reached`,
        'Stop loss hit',
        `Forced exit at ${forcedExitTime}`,
      ],
      config: {
        timing: {
          entryFrom,
          forcedExitTime,
          entryDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        },
        riskManagement: {
          maxLossPerTrade: `₹${maxLossPerTrade}`,
          riskRewardRatio: '1:2',
        },
        options: {
          strikeSelection: 'ATM',
          legs,
        },
        target: {
          value: target,
          scaleOutPlan: 'Book 50% at 1R and trail remaining 50% using EMA 8',
        },
      },
    };

    try {
      const res = await strategyApi.createStrategy(payload);
      addToast(`Strategy created successfully! ID: #${res.data?.id || 'NEW'}`, 'success');
      onNavigate('strategies');
    } catch (err) {
      addToast(err.message || 'Failed to create strategy', 'error');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px', maxWidth: '1000px', margin: '0 auto' }}>
      <div>
        <h1 style={{ fontSize: '1.8rem', fontWeight: 800, color: '#fff' }}>Visual Multi-Leg Strategy Builder</h1>
        <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>Design, backtest, and provision institutional option algorithms with automated schema validation.</p>
      </div>

      {/* AI Strategy Generator Card */}
      <div className="glass-panel" style={{ padding: '20px', border: '1px solid rgba(168, 85, 247, 0.4)', background: 'rgba(168, 85, 247, 0.05)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '10px' }}>
          <Sparkles size={20} color="var(--accent-purple)" />
          <h3 style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--accent-purple)' }}>AI Natural Language Strategy Generator</h3>
        </div>
        <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '12px' }}>
          Describe your strategy in plain English (e.g. <em>"Create an intraday 15m RSI 60 momentum breakout for Nifty with 2R profit target"</em>).
        </p>
        <div style={{ display: 'flex', gap: '10px' }}>
          <input
            type="text"
            placeholder="Type strategy prompt..."
            value={aiPrompt}
            onChange={(e) => setAiPrompt(e.target.value)}
            className="input-field"
          />
          <button
            onClick={handleAiGenerate}
            disabled={aiGenerating}
            className="btn"
            style={{ background: 'var(--accent-purple)', color: '#fff', whiteSpace: 'nowrap' }}
          >
            <Sparkles size={16} />
            <span>{aiGenerating ? 'Generating...' : 'AI Generate'}</span>
          </button>
        </div>
      </div>

      {/* Main Builder Form */}
      <form onSubmit={handleSaveStrategy} className="glass-panel" style={{ padding: '28px', display: 'flex', flexDirection: 'column', gap: '20px' }}>
        <h3 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#fff', borderBottom: '1px solid var(--border-subtle)', paddingBottom: '10px' }}>
          1. General & Instrument Configuration
        </h3>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
          <div>
            <label>Strategy Name</label>
            <input type="text" value={name} onChange={(e) => setName(e.target.value)} className="input-field" required />
          </div>
          <div>
            <label>Author</label>
            <input type="text" value={author} onChange={(e) => setAuthor(e.target.value)} className="input-field" />
          </div>
        </div>

        <div>
          <label>Description</label>
          <textarea
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            className="input-field"
            rows="2"
          />
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '16px' }}>
          <div>
            <label>Underlying Asset</label>
            <select value={underlying} onChange={(e) => setUnderlying(e.target.value)} className="input-field">
              <option value="NIFTY 50">NIFTY 50</option>
              <option value="BANKNIFTY">BANKNIFTY</option>
              <option value="FINNIFTY">FINNIFTY</option>
              <option value="RELIANCE">RELIANCE</option>
              <option value="HDFCBANK">HDFCBANK</option>
            </select>
          </div>
          <div>
            <label>Candle Timeframe</label>
            <select value={timeframe} onChange={(e) => setTimeframe(e.target.value)} className="input-field">
              <option value="1m">1 Minute</option>
              <option value="5m">5 Minutes</option>
              <option value="15m">15 Minutes</option>
              <option value="1d">Daily (1D)</option>
            </select>
          </div>
          <div>
            <label>Target (Profit Ceiling)</label>
            <input type="text" value={target} onChange={(e) => setTarget(e.target.value)} className="input-field" />
          </div>
          <div>
            <label>Max Loss Per Trade (₹)</label>
            <input type="number" value={maxLossPerTrade} onChange={(e) => setMaxLossPerTrade(e.target.value)} className="input-field" />
          </div>
        </div>

        <h3 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#fff', borderBottom: '1px solid var(--border-subtle)', paddingBottom: '10px', marginTop: '10px' }}>
          2. Multi-Leg Options Construction
        </h3>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
          {legs.map((leg, idx) => (
            <div key={idx} style={{
              display: 'grid',
              gridTemplateColumns: '100px 100px 1fr 100px 40px',
              gap: '12px',
              alignItems: 'center',
              background: 'var(--bg-input)',
              padding: '12px 16px',
              borderRadius: '8px',
              border: '1px solid var(--border-subtle)',
            }}>
              <div>
                <label style={{ fontSize: '0.7rem' }}>Action</label>
                <select value={leg.action} onChange={(e) => updateLeg(idx, 'action', e.target.value)} className="input-field">
                  <option value="BUY">BUY</option>
                  <option value="SELL">SELL</option>
                </select>
              </div>
              <div>
                <label style={{ fontSize: '0.7rem' }}>Option</label>
                <select value={leg.type} onChange={(e) => updateLeg(idx, 'type', e.target.value)} className="input-field">
                  <option value="CE">CALL (CE)</option>
                  <option value="PE">PUT (PE)</option>
                </select>
              </div>
              <div>
                <label style={{ fontSize: '0.7rem' }}>Strike Selection</label>
                <select value={leg.strike} onChange={(e) => updateLeg(idx, 'strike', e.target.value)} className="input-field">
                  <option value="ATM">At The Money (ATM)</option>
                  <option value="OTM +100">OTM (+100)</option>
                  <option value="OTM +200">OTM (+200)</option>
                  <option value="ITM -100">ITM (-100)</option>
                </select>
              </div>
              <div>
                <label style={{ fontSize: '0.7rem' }}>Lots</label>
                <input type="number" min="1" value={leg.quantity} onChange={(e) => updateLeg(idx, 'quantity', parseInt(e.target.value) || 1)} className="input-field" />
              </div>
              <button
                type="button"
                onClick={() => removeLeg(idx)}
                style={{ background: 'transparent', border: 'none', color: 'var(--accent-rose)', cursor: 'pointer', marginTop: '16px' }}
              >
                <Trash2 size={16} />
              </button>
            </div>
          ))}

          <button
            type="button"
            onClick={addLeg}
            className="btn btn-secondary"
            style={{ width: 'fit-content', fontSize: '0.8rem' }}
          >
            <Plus size={14} />
            <span>Add Trade Leg</span>
          </button>
        </div>

        <h3 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#fff', borderBottom: '1px solid var(--border-subtle)', paddingBottom: '10px', marginTop: '10px' }}>
          3. Timing & Intraday Cutoff Rules
        </h3>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
          <div>
            <label>Entry Window Start</label>
            <input type="time" value={entryFrom} onChange={(e) => setEntryFrom(e.target.value)} className="input-field" />
          </div>
          <div>
            <label>Forced Exit Cutoff Time</label>
            <input type="time" value={forcedExitTime} onChange={(e) => setForcedExitTime(e.target.value)} className="input-field" />
          </div>
        </div>

        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px', marginTop: '20px' }}>
          <button type="button" onClick={() => onNavigate('strategies')} className="btn btn-secondary">
            Cancel
          </button>
          <button type="submit" disabled={loading} className="btn btn-primary" style={{ padding: '10px 24px' }}>
            <CheckCircle size={18} />
            <span>{loading ? 'Validating & Saving...' : 'Save & Provision Strategy'}</span>
          </button>
        </div>
      </form>
    </div>
  );
};

export default StrategyBuilderPage;
