import enum

class StrategyStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    PAPER = "PAPER"
    ACTIVE_LIVE = "ACTIVE_LIVE"
    PAUSED = "PAUSED"
    STOPPED = "STOPPED"

class RuleType(str, enum.Enum):
    PRICE_COMPARISON = "PRICE_COMPARISON"
    PRICE_CROSSOVER = "PRICE_CROSSOVER"
    INDICATOR_COMPARISON = "INDICATOR_COMPARISON"
    INDICATOR_CROSSOVER = "INDICATOR_CROSSOVER"
    AND = "AND"
    OR = "OR"
    NOT = "NOT"

class EvaluationType(str, enum.Enum):
    CANDLE_CLOSE = "CANDLE_CLOSE"
    TICK = "TICK"

class StrategyLifecycleState(str, enum.Enum):
    WAITING = "WAITING"
    ELIGIBLE = "ELIGIBLE"
    MONITORING_ENTRY = "MONITORING_ENTRY"
    ENTRY_SIGNAL = "ENTRY_SIGNAL"
    ORDER_PENDING = "ORDER_PENDING"
    POSITION_OPEN = "POSITION_OPEN"
    MONITORING_EXIT = "MONITORING_EXIT"
    EXIT_SIGNAL = "EXIT_SIGNAL"
    EXIT_ORDER_PENDING = "EXIT_ORDER_PENDING"
    POSITION_CLOSED = "POSITION_CLOSED"
    PAUSED = "PAUSED"
    ERROR = "ERROR"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"

class StrategyHorizon(str, enum.Enum):
    INTRADAY = "INTRADAY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"

class ScheduleEvaluationReason(str, enum.Enum):
    WITHIN_ENTRY_WINDOW = "WITHIN_ENTRY_WINDOW"
    BEFORE_ENTRY_TIME = "BEFORE_ENTRY_TIME"
    AFTER_FORCED_EXIT_TIME = "AFTER_FORCED_EXIT_TIME"
    AFTER_ENTRY_TO_TIME = "AFTER_ENTRY_TO_TIME"
    DAY_NOT_APPLICABLE = "DAY_NOT_APPLICABLE"
    MONTH_NOT_APPLICABLE = "MONTH_NOT_APPLICABLE"
    DATE_NOT_APPLICABLE = "DATE_NOT_APPLICABLE"
    INVALID_SCHEDULE = "INVALID_SCHEDULE"


