"""add_rules_and_golden_rules_tables

Revision ID: 022b1c175d14
Revises: f0ee417c76c7
Create Date: 2026-08-29 17:05:31.068379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '022b1c175d14'
down_revision: Union[str, Sequence[str], None] = 'f0ee417c76c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_conditions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('strategy_version_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('rule_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_golden_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('strategy_version_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('evaluation', sa.String(length=50), nullable=False),
    sa.Column('confirmation', sa.String(length=100), nullable=False),
    sa.Column('timeframe', sa.String(length=30), nullable=False),
    sa.Column('rule_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'flyway_schema_history' in tables:
        op.drop_index(op.f('flyway_schema_history_s_idx'), table_name='flyway_schema_history')
        op.drop_table('flyway_schema_history')
        op.drop_constraint(op.f('dhan_broker_sessions_user_id_key'), 'dhan_broker_sessions', type_='unique')
        op.drop_index(op.f('idx_dhan_broker_sessions_conn_date'), table_name='dhan_broker_sessions')
        op.drop_index(op.f('idx_dhan_broker_sessions_dhan_client_id'), table_name='dhan_broker_sessions')
        op.drop_index(op.f('idx_dhan_broker_sessions_status'), table_name='dhan_broker_sessions')
        op.drop_index(op.f('idx_dhan_broker_sessions_user_id'), table_name='dhan_broker_sessions')
        op.create_index(op.f('ix_dhan_broker_sessions_dhan_client_id'), 'dhan_broker_sessions', ['dhan_client_id'], unique=False)
        op.create_index(op.f('ix_dhan_broker_sessions_status'), 'dhan_broker_sessions', ['status'], unique=False)
        op.create_index(op.f('ix_dhan_broker_sessions_user_id'), 'dhan_broker_sessions', ['user_id'], unique=True)
        op.drop_table_comment(
            'dhan_broker_sessions',
            existing_comment='Stores Dhan HQ access tokens, user metadata, and credentials. One row per platform user.',
            schema=None
        )
        op.drop_constraint(op.f('plan_features_plan_id_feature_code_key'), 'plan_features', type_='unique')
        op.create_unique_constraint('uq_plan_feature_code', 'plan_features', ['plan_id', 'feature_code'])
        op.drop_index(op.f('idx_plan_strategy_access_plan_strategy'), table_name='plan_strategy_access')
        op.drop_constraint(op.f('plan_strategy_access_plan_id_strategy_id_key'), 'plan_strategy_access', type_='unique')
        op.create_index(op.f('ix_plan_strategy_access_plan_id'), 'plan_strategy_access', ['plan_id'], unique=False)
        op.create_unique_constraint('uq_plan_strategy_access', 'plan_strategy_access', ['plan_id', 'strategy_id'])
        op.create_foreign_key(None, 'plan_strategy_access', 'strategies', ['strategy_id'], ['id'], ondelete='CASCADE')
        op.alter_column('plans', 'description',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.drop_constraint(op.f('plans_code_key'), 'plans', type_='unique')
        op.create_index(op.f('ix_plans_code'), 'plans', ['code'], unique=True)
        op.drop_index(op.f('idx_strategies_status'), table_name='strategies')
        op.drop_index(op.f('idx_strategies_user_id'), table_name='strategies')
        op.create_index(op.f('ix_strategies_status'), 'strategies', ['status'], unique=False)
        op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
        op.drop_column('strategies', 'updated_at')
        op.drop_column('strategies', 'created_at')
        op.create_index(op.f('ix_strategy_execution_batches_strategy_id'), 'strategy_execution_batches', ['strategy_id'], unique=False)
        op.create_index(op.f('ix_strategy_execution_trace_events_execution_trace_id'), 'strategy_execution_trace_events', ['execution_trace_id'], unique=False)
        op.create_index(op.f('ix_strategy_executions_strategy_id'), 'strategy_executions', ['strategy_id'], unique=False)
        op.create_index(op.f('ix_strategy_executions_user_id'), 'strategy_executions', ['user_id'], unique=False)
        op.create_index(op.f('ix_strategy_signals_strategy_id'), 'strategy_signals', ['strategy_id'], unique=False)
        op.drop_index(op.f('idx_execution_trace_batch'), table_name='strategy_user_execution_traces')
        op.drop_index(op.f('idx_execution_trace_correlation'), table_name='strategy_user_execution_traces')
        op.drop_index(op.f('idx_execution_trace_signal'), table_name='strategy_user_execution_traces')
        op.drop_index(op.f('idx_execution_trace_status'), table_name='strategy_user_execution_traces')
        op.drop_index(op.f('idx_execution_trace_user'), table_name='strategy_user_execution_traces')
        op.drop_index(op.f('uq_signal_user_execution_trace'), table_name='strategy_user_execution_traces')
        op.create_unique_constraint('uq_signal_user_execution_trace', 'strategy_user_execution_traces', ['signal_id', 'user_id'])
        op.create_index(op.f('ix_strategy_user_execution_traces_correlation_id'), 'strategy_user_execution_traces', ['correlation_id'], unique=False)
        op.create_index(op.f('ix_strategy_user_execution_traces_execution_batch_id'), 'strategy_user_execution_traces', ['execution_batch_id'], unique=False)
        op.create_index(op.f('ix_strategy_user_execution_traces_signal_id'), 'strategy_user_execution_traces', ['signal_id'], unique=False)
        op.create_index(op.f('ix_strategy_user_execution_traces_status'), 'strategy_user_execution_traces', ['status'], unique=False)
        op.create_index(op.f('ix_strategy_user_execution_traces_user_id'), 'strategy_user_execution_traces', ['user_id'], unique=False)
        op.drop_index(op.f('idx_subscription_events_subscription_id'), table_name='subscription_events')
        op.create_index(op.f('ix_subscription_events_subscription_id'), 'subscription_events', ['subscription_id'], unique=False)
        op.drop_index(op.f('idx_subscription_payments_provider_payment_id'), table_name='subscription_payments')
        op.drop_index(op.f('idx_subscription_payments_user_id'), table_name='subscription_payments')
        op.create_index(op.f('ix_subscription_payments_provider_payment_id'), 'subscription_payments', ['provider_payment_id'], unique=False)
        op.create_index(op.f('ix_subscription_payments_user_id'), 'subscription_payments', ['user_id'], unique=False)
        op.drop_index(op.f('idx_subscriptions_current_period_end'), table_name='subscriptions')
        op.drop_index(op.f('idx_subscriptions_status'), table_name='subscriptions')
        op.drop_index(op.f('idx_subscriptions_user_id'), table_name='subscriptions')
        op.create_index(op.f('ix_subscriptions_current_period_end'), 'subscriptions', ['current_period_end'], unique=False)
        op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
        op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
        op.drop_index(op.f('idx_user_daily_strategy_usage_user_date'), table_name='user_daily_strategy_usage')
        op.drop_constraint(op.f('user_daily_strategy_usage_user_id_trading_date_key'), 'user_daily_strategy_usage', type_='unique')
        op.create_index(op.f('ix_user_daily_strategy_usage_user_id'), 'user_daily_strategy_usage', ['user_id'], unique=False)
        op.create_unique_constraint('uq_user_daily_usage', 'user_daily_strategy_usage', ['user_id', 'trading_date'])
        op.drop_index(op.f('idx_user_fund_snapshots_user_date'), table_name='user_fund_snapshots')
        op.create_index(op.f('ix_user_fund_snapshots_user_id'), 'user_fund_snapshots', ['user_id'], unique=False)
        op.drop_index(op.f('idx_user_holdings_symbol'), table_name='user_holdings')
        op.drop_index(op.f('idx_user_holdings_user_id'), table_name='user_holdings')
        op.create_index(op.f('ix_user_holdings_trading_symbol'), 'user_holdings', ['trading_symbol'], unique=False)
        op.create_index(op.f('ix_user_holdings_user_id'), 'user_holdings', ['user_id'], unique=False)
        op.drop_index(op.f('idx_user_orders_status'), table_name='user_orders')
        op.drop_index(op.f('idx_user_orders_user_id'), table_name='user_orders')
        op.create_index(op.f('ix_user_orders_order_status'), 'user_orders', ['order_status'], unique=False)
        op.create_index(op.f('ix_user_orders_user_id'), 'user_orders', ['user_id'], unique=False)
        op.drop_index(op.f('idx_user_positions_user_id'), table_name='user_positions')
        op.create_index(op.f('ix_user_positions_user_id'), 'user_positions', ['user_id'], unique=False)
        op.drop_index(op.f('idx_user_trades_user_id'), table_name='user_trades')
        op.create_index(op.f('ix_user_trades_user_id'), 'user_trades', ['user_id'], unique=False)
        op.drop_index(op.f('idx_users_email'), table_name='users')
        op.drop_index(op.f('idx_users_referral_code'), table_name='users')
        op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
        op.drop_constraint(op.f('users_referral_code_key'), 'users', type_='unique')
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
        op.drop_index(op.f('idx_wallet_transactions_idempotency_key'), table_name='wallet_transactions')
        op.drop_index(op.f('idx_wallet_transactions_wallet_id'), table_name='wallet_transactions')
        op.drop_constraint(op.f('wallet_transactions_idempotency_key_key'), 'wallet_transactions', type_='unique')
        op.create_index(op.f('ix_wallet_transactions_idempotency_key'), 'wallet_transactions', ['idempotency_key'], unique=True)
        op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
        op.drop_constraint(op.f('wallet_transactions_wallet_id_fkey'), 'wallet_transactions', type_='foreignkey')
        op.create_foreign_key(None, 'wallet_transactions', 'wallets', ['wallet_id'], ['id'], ondelete='CASCADE')
        op.drop_index(op.f('idx_wallets_user_id'), table_name='wallets')
        op.drop_constraint(op.f('wallets_user_id_key'), 'wallets', type_='unique')
        op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.create_unique_constraint(op.f('wallets_user_id_key'), 'wallets', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.drop_constraint(None, 'wallet_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('wallet_transactions_wallet_id_fkey'), 'wallet_transactions', 'wallets', ['wallet_id'], ['id'])
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_idempotency_key'), table_name='wallet_transactions')
    op.create_unique_constraint(op.f('wallet_transactions_idempotency_key_key'), 'wallet_transactions', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_index(op.f('idx_wallet_transactions_idempotency_key'), 'wallet_transactions', ['idempotency_key'], unique=False)
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_referral_code_key'), 'users', ['referral_code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_referral_code'), 'users', ['referral_code'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_user_trades_user_id'), table_name='user_trades')
    op.create_index(op.f('idx_user_trades_user_id'), 'user_trades', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_positions_user_id'), table_name='user_positions')
    op.create_index(op.f('idx_user_positions_user_id'), 'user_positions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_orders_user_id'), table_name='user_orders')
    op.drop_index(op.f('ix_user_orders_order_status'), table_name='user_orders')
    op.create_index(op.f('idx_user_orders_user_id'), 'user_orders', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_orders_status'), 'user_orders', ['order_status'], unique=False)
    op.drop_index(op.f('ix_user_holdings_user_id'), table_name='user_holdings')
    op.drop_index(op.f('ix_user_holdings_trading_symbol'), table_name='user_holdings')
    op.create_index(op.f('idx_user_holdings_user_id'), 'user_holdings', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_holdings_symbol'), 'user_holdings', ['trading_symbol'], unique=False)
    op.drop_index(op.f('ix_user_fund_snapshots_user_id'), table_name='user_fund_snapshots')
    op.create_index(op.f('idx_user_fund_snapshots_user_date'), 'user_fund_snapshots', ['user_id', 'snapshot_date'], unique=False)
    op.drop_constraint('uq_user_daily_usage', 'user_daily_strategy_usage', type_='unique')
    op.drop_index(op.f('ix_user_daily_strategy_usage_user_id'), table_name='user_daily_strategy_usage')
    op.create_unique_constraint(op.f('user_daily_strategy_usage_user_id_trading_date_key'), 'user_daily_strategy_usage', ['user_id', 'trading_date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_daily_strategy_usage_user_date'), 'user_daily_strategy_usage', ['user_id', 'trading_date'], unique=False)
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_current_period_end'), table_name='subscriptions')
    op.create_index(op.f('idx_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('idx_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('idx_subscriptions_current_period_end'), 'subscriptions', ['current_period_end'], unique=False)
    op.drop_index(op.f('ix_subscription_payments_user_id'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_provider_payment_id'), table_name='subscription_payments')
    op.create_index(op.f('idx_subscription_payments_user_id'), 'subscription_payments', ['user_id'], unique=False)
    op.create_index(op.f('idx_subscription_payments_provider_payment_id'), 'subscription_payments', ['provider_payment_id'], unique=False)
    op.drop_index(op.f('ix_subscription_events_subscription_id'), table_name='subscription_events')
    op.create_index(op.f('idx_subscription_events_subscription_id'), 'subscription_events', ['subscription_id'], unique=False)
    op.drop_index(op.f('ix_strategy_user_execution_traces_user_id'), table_name='strategy_user_execution_traces')
    op.drop_index(op.f('ix_strategy_user_execution_traces_status'), table_name='strategy_user_execution_traces')
    op.drop_index(op.f('ix_strategy_user_execution_traces_signal_id'), table_name='strategy_user_execution_traces')
    op.drop_index(op.f('ix_strategy_user_execution_traces_execution_batch_id'), table_name='strategy_user_execution_traces')
    op.drop_index(op.f('ix_strategy_user_execution_traces_correlation_id'), table_name='strategy_user_execution_traces')
    op.drop_constraint('uq_signal_user_execution_trace', 'strategy_user_execution_traces', type_='unique')
    op.create_index(op.f('uq_signal_user_execution_trace'), 'strategy_user_execution_traces', ['signal_id', 'user_id'], unique=True)
    op.create_index(op.f('idx_execution_trace_user'), 'strategy_user_execution_traces', ['user_id'], unique=False)
    op.create_index(op.f('idx_execution_trace_status'), 'strategy_user_execution_traces', ['status'], unique=False)
    op.create_index(op.f('idx_execution_trace_signal'), 'strategy_user_execution_traces', ['signal_id'], unique=False)
    op.create_index(op.f('idx_execution_trace_correlation'), 'strategy_user_execution_traces', ['correlation_id'], unique=False)
    op.create_index(op.f('idx_execution_trace_batch'), 'strategy_user_execution_traces', ['execution_batch_id'], unique=False)
    op.drop_index(op.f('ix_strategy_signals_strategy_id'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_executions_user_id'), table_name='strategy_executions')
    op.drop_index(op.f('ix_strategy_executions_strategy_id'), table_name='strategy_executions')
    op.drop_index(op.f('ix_strategy_execution_trace_events_execution_trace_id'), table_name='strategy_execution_trace_events')
    op.drop_index(op.f('ix_strategy_execution_batches_strategy_id'), table_name='strategy_execution_batches')
    op.add_column('strategies', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('strategies', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_status'), table_name='strategies')
    op.create_index(op.f('idx_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.create_index(op.f('idx_strategies_status'), 'strategies', ['status'], unique=False)
    op.drop_index(op.f('ix_plans_code'), table_name='plans')
    op.create_unique_constraint(op.f('plans_code_key'), 'plans', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('plans', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'plan_strategy_access', type_='foreignkey')
    op.drop_constraint('uq_plan_strategy_access', 'plan_strategy_access', type_='unique')
    op.drop_index(op.f('ix_plan_strategy_access_plan_id'), table_name='plan_strategy_access')
    op.create_unique_constraint(op.f('plan_strategy_access_plan_id_strategy_id_key'), 'plan_strategy_access', ['plan_id', 'strategy_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_plan_strategy_access_plan_strategy'), 'plan_strategy_access', ['plan_id', 'strategy_id'], unique=False)
    op.drop_constraint('uq_plan_feature_code', 'plan_features', type_='unique')
    op.create_unique_constraint(op.f('plan_features_plan_id_feature_code_key'), 'plan_features', ['plan_id', 'feature_code'], postgresql_nulls_not_distinct=False)
    op.create_table_comment(
        'dhan_broker_sessions',
        'Stores Dhan HQ access tokens, user metadata, and credentials. One row per platform user.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_dhan_broker_sessions_user_id'), table_name='dhan_broker_sessions')
    op.drop_index(op.f('ix_dhan_broker_sessions_status'), table_name='dhan_broker_sessions')
    op.drop_index(op.f('ix_dhan_broker_sessions_dhan_client_id'), table_name='dhan_broker_sessions')
    op.create_index(op.f('idx_dhan_broker_sessions_user_id'), 'dhan_broker_sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_dhan_broker_sessions_status'), 'dhan_broker_sessions', ['status'], unique=False)
    op.create_index(op.f('idx_dhan_broker_sessions_dhan_client_id'), 'dhan_broker_sessions', ['dhan_client_id'], unique=False)
    op.create_index(op.f('idx_dhan_broker_sessions_conn_date'), 'dhan_broker_sessions', ['user_id', 'connection_date'], unique=False)
    op.create_unique_constraint(op.f('dhan_broker_sessions_user_id_key'), 'dhan_broker_sessions', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_table('flyway_schema_history',
    sa.Column('installed_rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('script', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('installed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('installed_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('execution_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('installed_rank', name=op.f('flyway_schema_history_pk'))
    )
    op.create_index(op.f('flyway_schema_history_s_idx'), 'flyway_schema_history', ['success'], unique=False)
    op.drop_table('strategy_golden_rules')
    op.drop_table('strategy_conditions')
    # ### end Alembic commands ###
