"""extend_strategy_signal_for_event_driven_execution

Revision ID: 229aa5279937
Revises: 3ecf70092a23
Create Date: 2026-09-01 12:04:02.928451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '229aa5279937'
down_revision: Union[str, Sequence[str], None] = '3ecf70092a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uk_strategy_execution_legs_correlation_id'), 'strategy_execution_legs', type_='unique')
    op.create_index(op.f('ix_strategy_execution_legs_broker_order_id'), 'strategy_execution_legs', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_strategy_execution_legs_correlation_id'), 'strategy_execution_legs', ['correlation_id'], unique=True)
    op.add_column('strategy_signals', sa.Column('signal_key', sa.String(length=255), nullable=True))
    op.add_column('strategy_signals', sa.Column('market_event_key', sa.String(length=255), nullable=True))
    op.add_column('strategy_signals', sa.Column('signal_type', sa.String(length=20), server_default='ENTRY', nullable=False))
    op.add_column('strategy_signals', sa.Column('direction', sa.String(length=20), server_default='BUY', nullable=False))
    op.add_column('strategy_signals', sa.Column('status', sa.String(length=30), server_default='CREATED', nullable=False))
    op.add_column('strategy_signals', sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('strategy_signals', sa.Column('reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_strategy_signals_market_event_key'), 'strategy_signals', ['market_event_key'], unique=False)
    op.create_index(op.f('ix_strategy_signals_signal_key'), 'strategy_signals', ['signal_key'], unique=True)
    op.add_column('user_fund_snapshots', sa.Column('account_client_id', sa.String(length=100), nullable=True))
    op.drop_column('user_fund_snapshots', 'dhan_client_id')
    op.alter_column('user_orders', 'broker_order_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(op.f('uk_user_orders_correlation_id'), 'user_orders', type_='unique')
    op.create_index(op.f('ix_user_orders_broker_order_id'), 'user_orders', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_user_orders_correlation_id'), 'user_orders', ['correlation_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_orders_correlation_id'), table_name='user_orders')
    op.drop_index(op.f('ix_user_orders_broker_order_id'), table_name='user_orders')
    op.create_unique_constraint(op.f('uk_user_orders_correlation_id'), 'user_orders', ['correlation_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_orders', 'broker_order_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('user_fund_snapshots', sa.Column('dhan_client_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('user_fund_snapshots', 'account_client_id')
    op.drop_index(op.f('ix_strategy_signals_signal_key'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_market_event_key'), table_name='strategy_signals')
    op.drop_column('strategy_signals', 'reason')
    op.drop_column('strategy_signals', 'price')
    op.drop_column('strategy_signals', 'status')
    op.drop_column('strategy_signals', 'direction')
    op.drop_column('strategy_signals', 'signal_type')
    op.drop_column('strategy_signals', 'market_event_key')
    op.drop_column('strategy_signals', 'signal_key')
    op.drop_index(op.f('ix_strategy_execution_legs_correlation_id'), table_name='strategy_execution_legs')
    op.drop_index(op.f('ix_strategy_execution_legs_broker_order_id'), table_name='strategy_execution_legs')
    op.create_unique_constraint(op.f('uk_strategy_execution_legs_correlation_id'), 'strategy_execution_legs', ['correlation_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
