"""add_runtime_state_and_event_processing

Revision ID: c96b9843feb6
Revises: 022b1c175d14
Create Date: 2026-08-31 16:23:11.959755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c96b9843feb6'
down_revision: Union[str, Sequence[str], None] = '022b1c175d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_event_processing',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.BigInteger(), nullable=False),
    sa.Column('market_event_key', sa.String(length=255), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_event_processing_market_event_key'), 'strategy_event_processing', ['market_event_key'], unique=True)
    op.create_index(op.f('ix_strategy_event_processing_strategy_id'), 'strategy_event_processing', ['strategy_id'], unique=False)
    op.create_table('strategy_runtime_states',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.BigInteger(), nullable=False),
    sa.Column('strategy_version_id', sa.BigInteger(), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=50), nullable=False),
    sa.Column('paused_from_state', sa.String(length=50), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monitoring_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monitoring_stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_runtime_states_strategy_id'), 'strategy_runtime_states', ['strategy_id'], unique=True)
    op.create_index(op.f('ix_strategy_runtime_states_strategy_version_id'), 'strategy_runtime_states', ['strategy_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_runtime_states_strategy_version_id'), table_name='strategy_runtime_states')
    op.drop_index(op.f('ix_strategy_runtime_states_strategy_id'), table_name='strategy_runtime_states')
    op.drop_table('strategy_runtime_states')
    op.drop_index(op.f('ix_strategy_event_processing_strategy_id'), table_name='strategy_event_processing')
    op.drop_index(op.f('ix_strategy_event_processing_market_event_key'), table_name='strategy_event_processing')
    op.drop_table('strategy_event_processing')
    # ### end Alembic commands ###
