import enum

class RouteType(str, enum.Enum):
    ENTRY = "ENTRY"
    EXIT = "EXIT"

class RouteSkipReason(str, enum.Enum):
    INACTIVE_STRATEGY = "INACTIVE_STRATEGY"
    INVALID_RUNTIME_STATE = "INVALID_RUNTIME_STATE"
    SYMBOL_MISMATCH = "SYMBOL_MISMATCH"
    SECURITY_ID_MISMATCH = "SECURITY_ID_MISMATCH"
    TIMEFRAME_MISMATCH = "TIMEFRAME_MISMATCH"
    NOT_MONITORING = "NOT_MONITORING"
    VERSION_NOT_FOUND = "VERSION_NOT_FOUND"
    SCHEDULE_NOT_ELIGIBLE = "SCHEDULE_NOT_ELIGIBLE"
