import enum

class RiskDecisionType(str, enum.Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"

class RiskCheckType(str, enum.Enum):
    SIGNAL_VALIDATION = "SIGNAL_VALIDATION"
    STRATEGY_ACTIVE = "STRATEGY_ACTIVE"
    USER_ACTIVE = "USER_ACTIVE"
    SUBSCRIPTION_ACCESS = "SUBSCRIPTION_ACCESS"
    BROKER_CONNECTION = "BROKER_CONNECTION"
    MAX_OPEN_POSITIONS = "MAX_OPEN_POSITIONS"
    DAILY_TRADE_LIMIT = "DAILY_TRADE_LIMIT"
    COOLDOWN_PERIOD = "COOLDOWN_PERIOD"
    CONSECUTIVE_LOSS_LIMIT = "CONSECUTIVE_LOSS_LIMIT"
    DAILY_LOSS_LIMIT = "DAILY_LOSS_LIMIT"
    WEEKLY_LOSS_LIMIT = "WEEKLY_LOSS_LIMIT"
    CAPITAL_AND_MARGIN = "CAPITAL_AND_MARGIN"
    BALANCE_50_PCT_RULE = "BALANCE_50_PCT_RULE"
    QUOTA_RESERVATION = "QUOTA_RESERVATION"
    FINAL_APPROVAL = "FINAL_APPROVAL"

class RiskFailureCode(str, enum.Enum):
    SIGNAL_INVALID = "SIGNAL_INVALID"
    STRATEGY_DISABLED = "STRATEGY_DISABLED"
    USER_INACTIVE = "USER_INACTIVE"
    PLAN_NOT_ALLOWED = "PLAN_NOT_ALLOWED"
    BROKER_SESSION_INVALID = "BROKER_SESSION_INVALID"
    BROKER_SESSION_NOT_FOUND = "BROKER_SESSION_NOT_FOUND"
    BROKER_SESSION_EXPIRED = "BROKER_SESSION_EXPIRED"
    MAX_POSITIONS_REACHED = "MAX_POSITIONS_REACHED"
    DAILY_LIMIT_REACHED = "DAILY_LIMIT_REACHED"
    COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
    CONSECUTIVE_LOSS_LIMIT_REACHED = "CONSECUTIVE_LOSS_LIMIT_REACHED"
    DAILY_LOSS_LIMIT_REACHED = "DAILY_LOSS_LIMIT_REACHED"
    WEEKLY_LOSS_LIMIT_REACHED = "WEEKLY_LOSS_LIMIT_REACHED"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    ORDER_EXCEEDS_50_PCT_BALANCE = "ORDER_EXCEEDS_50_PCT_BALANCE"
    FUNDS_DATA_UNAVAILABLE = "FUNDS_DATA_UNAVAILABLE"
    POSITION_STATE_UNAVAILABLE = "POSITION_STATE_UNAVAILABLE"
    PNL_STATE_UNAVAILABLE = "PNL_STATE_UNAVAILABLE"
    RESERVATION_FAILED = "RESERVATION_FAILED"

class RiskSizingMode(str, enum.Enum):
    FIXED_LOTS = "FIXED_LOTS"
    RISK_BASED = "RISK_BASED"
    CAPITAL_ALLOCATION = "CAPITAL_ALLOCATION"
